name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DISPLAY: ":100"

#TODO: factorize every defaults by putting it here

jobs:
  format-verify:
    runs-on: ubuntu-latest

    defaults: 
      run:
        shell: bash
        working-directory: ./LampColorControler 

    steps:
    - uses: actions/checkout@v4
      with:
        path: LampColorControler
        submodules: 'true'
    - name: verify format
      run : make format-verify

  Documentation:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: ./LampColorControler

    steps:
    - uses: actions/checkout@v4
      with:
        path: LampColorControler
        submodules: 'true'
    - name: Documentation
      run :
        sudo apt install doxygen -y &&
        make doc
  
  build-lamp:
    runs-on: ubuntu-latest
    needs: [format-verify]

    defaults:
      run:
        shell: bash
        working-directory: ./LampColorControler

    steps:
    - uses: actions/checkout@v4
      with:
        path: LampColorControler
        submodules: 'true'

    - name: setup
      run :
        make mr_proper arduino-cli-download safe-install
    - name: simple led strip build
      run : make simple
    - name: cct led strip build
      run : make cct
    - name: indexable led strip build
      run : make indexable
   
  
  build-simulator:
    runs-on: ubuntu-latest
    needs: [format-verify]

    defaults:
      run:
        shell: bash
        working-directory: ./LampColorControler

    steps:
    - uses: actions/checkout@v4
      with:
        path: LampColorControler
        submodules: 'true'

    - name: setup
      run :
         sudo apt update && 
         sudo apt install xorg-dev libxrandr-dev -y 
    - name: build
      run:
        Xvfb $DISPLAY -screen 0 1920x1080x24 &
        sleep 5 &&
        make simulator
