name: Lamp-Da Simulator main branch CI

on:
  push:
    paths:
      - "simulator/**"

defaults: 
  run:
    shell: bash
    working-directory: ./LampColorControler 

jobs:
  format-verify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: LampColorControler
        submodules: 'true'
    - name: verify format
      run : make format-verify

  build-simulator:
    runs-on: ubuntu-latest
    needs: [format-verify]

    steps:
    - uses: actions/checkout@v4
      with:
        path: LampColorControler
        submodules: 'true'

    - name: setup
      run :
         sudo apt update && 
         sudo apt install libx11-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libfreetype-dev libvorbis-dev libflac-dev libgl1-mesa-dev -y 
    - name: build
      run:
        make simulator
